---
- name: Set up arch box
  hosts: all
  roles:
    - system
    - role: disks
    # A little redundant, but I typo this enough to have both
      when:
        - "'vm' not in group_names"
        - "'vms' not in group_names"
        - "'pi' not in group_names"
        - "'pis' not in group_names"
    - editor
    #   - mounts
    - backups
    #   - containers
    - terminal
    - role: artis3n.tailscale.machine
      when: "'tailscale' in group_names"
      tags: tailscale
    - notifications
    - file_manager
    #   - reverse_proxy
    - drift_management
